export const PlaceholderValues = {
  firstName: "First Name",
  lastName: "Last name",
  emailAddress: "Email Address",
  address: "Address",
  phone: "Phone",
  position: "Job Position",
  companyName: "Company Name",
  location: "Location",
  schoolName: "School/University",
  degree: "Degree",
  grade: "Grade",
  description: "Description",
  start: "Start",
  end: "End",
  link: "https://www.example.com",
};
